function prettyplot(hXLabel,hYLabel,legh)

if ~isnan(legh)
    M = findobj(legh,'type','line');
    m=findobj(legh);
    set([legh],'FontName'   , 'Helvetica','TextColor',[.3 .3 .3] )
end

hands=[hXLabel hYLabel];
hands(isnan(hands))=[];

set( gca                       , ...
    'FontName'   , 'Helvetica','FontSize',40 );
set(hands, ...
    'FontName'   , 'Helvetica','Color',[.3 .3 .3] );
set(gca,'box','off')
set(hands  , ...
    'FontSize'   , 50          );
set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.02 .02] , ...
    'YMinorTick'  , 'on'      , ...
    'YGrid'       , 'on'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'LineWidth'   , 1         );
